<?php

/**
 * @file
 * Install hooks implementation.
 */

use \Drupal\plug_field\PlugFieldTypeManager;

/**
 * Implements hook_enable().
 */
function plug_field_enable() {
  variable_set('composer_manager_autoloader_bootstrap', 0);
}

/**
 * Implements hook_field_schema().
 */
function plug_field_field_schema($field) {
  return PlugFieldTypeManager::get()->createInstance($field['type'])->schema($field);
}
