<?php
/**
 * @file
 * Module implementation File.
 */

/**
 * Implements hook_field_formatter_info().
 */
function plug_formatter_field_formatter_info() {
  $formatter_manager = \Drupal\plug_formatter\PlugFormatterManager::create();
  $plugins = $formatter_manager->getDefinitions();
  $formatter_info =  array();

  foreach ($plugins as $name => $plugin) {
    $formatter_info[$name] = $plugin;
  }

  return $formatter_info;
}

/**
 * Implements hook_field_formatter_settings_form().
 */
function plug_formatter_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  $display = $instance['display'][$view_mode];
  $formatter_manager = \Drupal\plug_formatter\PlugFormatterManager::create();
  if ($plugin = $formatter_manager->createInstance($display['type'])) {
    return $plugin->settingsForm($field, $instance, $view_mode, $form, $form_state);
  }

}

/**
 * Implements hook_field_formatter_settings_summary().
 */
function plug_formatter_field_formatter_settings_summary($field, $instance, $view_mode) {
  $display = $instance['display'][$view_mode];
  $summary = array();

  $formatter_manager = \Drupal\plug_formatter\PlugFormatterManager::create();
  if ($plugin = $formatter_manager->createInstance($display['type'])) {
    $summary =  $plugin->settingsSummary($field, $instance, $view_mode);
  }

  return implode('<br />', $summary);
}

/**
 * Implements hook_field_formatter_view().
 */
function plug_formatter_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $formatter_manager = \Drupal\plug_formatter\PlugFormatterManager::create();
  if ($plugin = $formatter_manager->createInstance($display['type'])) {
    return $plugin->viewElements($entity_type, $entity, $field, $instance, $langcode, $items, $display);
  }

  return array();
}
