<?php
/**
 * @file
 * Module implementation File.
 */

use \Drupal\plug_widget\PlugFieldWidgetManager;

/**
 * Implements hook_field_widget_info().
 */
function plug_widget_field_widget_info() {
  return PlugFieldWidgetManager::create()->getDefinitions();
}

/**
 * Implements hook_field_widget_settings_form().
 */
function plug_widget_field_widget_settings_form($field, $instance) {
  $widget = $instance['widget'];
  if ($plugin = PlugFieldWidgetManager::create()->createInstance($widget['type'])) {
    return $plugin->settingsForm($field, $instance);
  }
}

/**
 * Implements hook_field_widget_form().
 */
function plug_widget_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  $widget = $instance['widget'];
  if ($plugin = PlugFieldWidgetManager::create()->createInstance($widget['type'])) {
    return $plugin->widgetForm($form, $form_state, $field, $instance, $langcode, $items, $delta, $element);
  }
}

/**
 * Implements hook_field_widget_error().
 */
function plug_widget_field_widget_error($element, $error, $form, &$form_state) {
  form_error($error_element, $error['message']);
}
