<?php
/**
 * @file
 * Module implementation File.
 */

use \Drupal\plug_field\FieldDefinition;
use \Drupal\plug_field\FieldInstanceDefinition;
use \Drupal\plug_widget\PlugFieldWidgetManager;

/**
 * Implements hook_field_widget_info().
 */
function plug_widget_field_widget_info() {
  return PlugFieldWidgetManager::get()->getDefinitions();
}

/**
 * Implements hook_field_widget_settings_form().
 */
function plug_widget_field_widget_settings_form($field, $instance) {
  $widget = $instance['widget'];
  if ($plugin = PlugFieldWidgetManager::get()->createInstance($widget['type'], array(
    'fieldDefinition' => new FieldDefinition($field),
    'fieldInstanceDefinition' => new FieldInstanceDefinition($instance),
  ))) {
    return $plugin->settingsForm();
  }
}

/**
 * Implements hook_field_widget_form().
 */
function plug_widget_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  $widget = $instance['widget'];
  if ($plugin = PlugFieldWidgetManager::get()->createInstance($widget['type'], array(
    'fieldDefinition' => new FieldDefinition($field),
    'fieldInstanceDefinition' => new FieldInstanceDefinition($instance),
  ))) {
    return $plugin->widgetForm($form, $form_state, $langcode, $items, $delta, $element);
  }
}
